# Generated by Django 4.2 on 2023-04-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
