# Generated by Django 4.2 on 2023-04-22 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_song_duration_song_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralbuns',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album'),
        ),
    ]
