# Generated by Django 4.2 on 2023-04-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_useralbuns_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='url',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
