# Generated by Django 4.1.7 on 2023-05-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_likes_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='type',
            field=models.IntegerField(choices=[(1, 'up_like'), (-1, 'down_like')], default=1),
        ),
    ]
