# Generated by Django 4.1.7 on 2023-05-16 00:37

from django.db import migrations, models
import user_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_alter_appuser_about_me_alter_appuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_pic',
            field=models.ImageField(default=None, null=True, upload_to=user_api.models.user_directory_path),
        ),
    ]
